apiVersion: kubeflow.org/v1
kind: TFJob
metadata:
  generateName: tfjob-multi-
  namespace: tf-distributed
spec:
  cleanPodPolicy: Running
  tfReplicaSpecs:
    Worker:
      replicas: 2
      restartPolicy: Never
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:            
          containers:
          - name: tensorflow
            image: "quay.io/selbi/ubi-cuda-tf-mnist:1.3"
            command: ["python3", "/home/mnist/src/main.py"] 
            imagePullPolicy: Always
            env:
              - name: TF_FORCE_GPU_ALLOW_GROWTH
                value: "true"
            resources:
                limits:
                    nvidia.com/gpu: 3
